database: postgres
spring:
  datasource:
    username: ${POSTGRES_USER:petclinic}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost/petclinic}
    password: ${POSTGRES_PASS:petclinic}
  sql:
    init:
      mode: always
